---
linters-settings:
  misspell:
    locale: "US"
  lll:
    line-length: 170

run:
  skip-dirs:
    - example/server

linters:
  enable:
    - bodyclose
    - containedctx
    - depguard
    - errcheck
    - exhaustive
    - exportloopref
    - gocritic
    - goimports
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace
